### ISSUE TITLE
This webmail client only for one user?

### ISSUE THREAD

**Issue by uitlaber** [afterlogic/webmail-lite#49]
This webmail client only for one user?

**Comment by mailbee** [comment]
User number is unlimited, can be thousands.

**Comment by uitlaber** [comment]
[20:56:53.11][1b07eec9] SMTP[NOTE]: Start connection to "ssl://mail.post.af:465"
[20:56:53.11][1b07eec9] SMTP[NOTICE]: Socket: [2] stream_socket_client(): unable to connect to ssl://mail.post.af:465 (Connection refused)
[20:56:53.11][1b07eec9] SMTP[NOTICE]: exception 'MailSo\Net\Exceptions\SocketCanNotConnectToHostException' with message 'Can't connect to host "ssl://mail.post.af:465"' in /var/www/post.af/mail/libraries/MailSo/Net/NetClient.php:283
Stack trace:
#0 /var/www/post.af/mail/libraries/MailSo/Smtp/SmtpClient.php(164): MailSo\Net\NetClient->Connect('mail.post.af', 465, 1, false)
#1 /var/www/post.af/mail/libraries/afterlogic/common/managers/mail/manager.php(1150): MailSo\Smtp\SmtpClient->Connect('mail.post.af', 465, 'post.af', 1, false)
#2 /var/www/post.af/mail/libraries/ProjectCore/Actions.php(1598): CApiMailManager->sendMessage(Object(CAccount), Object(MailSo\Mime\Message), NULL, 'Sent', '', '')
#3 [internal function]: ProjectCore\Actions->AjaxMessageSend()
#4 /var/www/post.af/mail/libraries/ProjectCore/Service.php(341): call_user_func(Array)
#5 /var/www/post.af/mail/libraries/ProjectCore/Boot.php(12): ProjectCore\Service->Handle()
#6 /var/www/post.af/mail/index.php(104): include('/var/www/post.a...')
#7 {main}
[20:56:53.11][1b07eec9] Previous Exception: Can't connect to host "ssl://mail.post.af:465"
[20:56:53.11][1b07eec9] exception 'CApiManagerException' with message 'Connect to mail server failed' in /var/www/post.af/mail/libraries/afterlogic/common/managers/mail/manager.php:1175
Stack trace:
#0 /var/www/post.af/mail/libraries/ProjectCore/Actions.php(1598): CApiMailManager->sendMessage(Object(CAccount), Object(MailSo\Mime\Message), NULL, 'Sent', '', '')
#1 [internal function]: ProjectCore\Actions->AjaxMessageSend()
#2 /var/www/post.af/mail/libraries/ProjectCore/Service.php(341): call_user_func(Array)
#3 /var/www/post.af/mail/libraries/ProjectCore/Boot.php(12): ProjectCore\Service->Handle()
#4 /var/www/post.af/mail/index.php(104): include('/var/www/post.a...')
#5 {main}

Next exception 'ProjectCore\Exceptions\ClientException' with message 'Can't connect to host "ssl://mail.post.af:465"' in /var/www/post.af/mail/libraries/ProjectCore/Actions.php:1619
Stack trace:
#0 [internal function]: ProjectCore\Actions->AjaxMessageSend()
#1 /var/www/post.af/mail/libraries/ProjectCore/Service.php(341): call_user_func(Array)
#2 /var/www/post.af/mail/libraries/ProjectCore/Boot.php(12): ProjectCore\Service->Handle()
#3 /var/www/post.af/mail/index.php(104): include('/var/www/post.a...')
#4 {main}
[20:56:53.11][1b07eec9] INFO[MEMORY]: Memory peak usage: 50.75MB
[20:56:53.11][1b07eec9] INFO[TIME]: Time delta: 0.12535119056702
[20:56:53.11][1b07eec9] DB : disconnect from root@localhost
[20:56:53.11][1b07eec9] IMAP[DATA]: > TAG2 LOGOUT\r\n
[20:56:53.11][1b07eec9] IMAP[DATA]: < * BYE Logging out\r\n
[20:56:53.11][1b07eec9] IMAP[DATA]: < TAG2 OK Logout completed.\r\n
[20:56:53.11][1b07eec9] IMAP[NOTE]: Disconnected from "ssl://mail.post.af:993" (success)

[20:56:53.27][99d3a278] [POST(9)][ip:127.0.0.1] /mail/?/Ajax/
[20:56:53.27][99d3a278] POST > [Action, Folder, Offset, Limit, Search, Filters, UseThreads, AccountID, Token]
[20:56:53.27][99d3a278]

**Comment by uitlaber** [comment]
i replaced real domain name for mydomain

**Comment by mailbee** [comment]
I tried your mail.post.** host, there is no port 465 open, you're trying to connect to a closed port. Please note that this is not a support forum, it's a place where to submit bugs found in this open source product. If you're interested in getting technical support from Afterlogic, please use http://helpdesk.afterlogic.com/ to learn more on support options available. Thanks!
