### ISSUE TITLE
302 When try to send an email

### ISSUE THREAD

**Issue by iamchathu** [afterlogic/webmail-lite#69]
I just installed  and configured webmail lite using script installer in CPanel.

I can login to my email and IMAP works perfectly I receive emails without any error. But when I try to send an email it gives me 302 Authentication error.Log file is as following.

```

[04:49:07.06][548cf891] [POST(19)][ip:172.68.201.23] /?/Ajax/
[04:49:07.06][548cf891] POST > [AccountID, FetcherID, IdentityID, DraftUid, To, Cc, Bcc, Subject, Text, IsHtml, Importance, Sensitivity, ReadingConfirmation, InReplyTo, References, Action, ShowReport, SentFolder, Token]
[04:49:07.06][548cf891]
[04:49:07.06][548cf891] Previous Exception: 535 Incorrect authentication data
[04:49:07.07][548cf891] exception 'CApiManagerException' with message 'Unknown error' in /home/imchathu/public_html/nwmlgens/libraries/afterlogic/common/managers/mail/manager.php:1194
Stack trace:
#0 /home/imchathu/public_html/nwmlgens/libraries/ProjectCore/Actions.php(1644): CApiMailManager->sendMessage(Object(CAccount), Object(MailSo\Mime\Message), NULL, 'INBOX.Sent', '', '')
#1 [internal function]: ProjectCore\Actions->AjaxMessageSend()
#2 /home/imchathu/public_html/nwmlgens/libraries/ProjectCore/Service.php(341): call_user_func(Array)
#3 /home/imchathu/public_html/nwmlgens/libraries/ProjectCore/Boot.php(12): ProjectCore\Service->Handle()
#4 /home/imchathu/public_html/nwmlgens/index.php(104): include('/home/imchathu/...')
#5 {main}

Next exception 'ProjectCore\Exceptions\ClientException' with message '535 Incorrect authentication data' in /home/imchathu/public_html/nwmlgens/libraries/ProjectCore/Actions.php:1665
Stack trace:
#0 [internal function]: ProjectCore\Actions->AjaxMessageSend()
#1 /home/imchathu/public_html/nwmlgens/libraries/ProjectCore/Service.php(341): call_user_func(Array)
#2 /home/imchathu/public_html/nwmlgens/libraries/ProjectCore/Boot.php(12): ProjectCore\Service->Handle()
#3 /home/imchathu/public_html/nwmlgens/index.php(104): include('/home/imchathu/...')
#4 {main}
```

The SMTP credentials also same as IMAP and same settings work well with Outlook app and mobile apps.

**Comment by afterlogic-support** [comment]
These log do not hold the context, make sure to set log verbosity to Debug and recreate rthe logs.

Also, is my understanding correct that you used the regular ZIP package and not the cPanel installer?

**Comment by afterlogic-support** [comment]
To assist you with that, we would need a test account on your installation, and admin credentials. If that's possible, please open a ticket via HelpDesk: http://helpdesk.afterlogic.com/
