### ISSUE TITLE
MailSo\Net\Exceptions\SocketConnectionDoesNotAvailableException

### ISSUE THREAD

**Issue by AldoSouzaNeto** [afterlogic/webmail-lite#87]
The error occurs only when attaching files to the email:

[12:05:33.41][3a3664f4] [POST(4)][ip:186.209.8.58] /cpsess3852505966/3rdparty/afterlogic/index.php?/Api/
[12:05:33.41][3a3664f4] POST > [Module, Method, TenantName, Parameters]
[12:05:33.41][3a3664f4]
[12:05:33.41][3a3664f4] exception 'MailSo\Net\Exceptions\SocketConnectionDoesNotAvailableException' with message 'MailSo-Net-Exceptions-SocketConnectionDoesNotAvailableException' in /usr/local/cpanel/base/3rdparty/afterlogic/vendor/afterlogic/mailso/lib/MailSo/Net/NetClient.php:368
Stack trace:
#0 /usr/local/cpanel/base/3rdparty/afterlogic/vendor/afterlogic/mailso/lib/MailSo/Imap/ImapClient.php(1655): MailSo\Net\NetClient->IsConnected(true)
#1 /usr/local/cpanel/base/3rdparty/afterlogic/vendor/afterlogic/mailso/lib/MailSo/Imap/ImapClient.php(1709): MailSo\Imap\ImapClient->SendRequest('LOGIN', Array)
#2 /usr/local/cpanel/base/3rdparty/afterlogic/vendor/afterlogic/mailso/lib/MailSo/Imap/ImapClient.php(271): MailSo\Imap\ImapClient->SendRequestWithCheck('LOGIN', Array)
#3 /usr/local/cpanel/base/3rdparty/afterlogic/modules/Mail/Managers/Main/Manager.php(126): MailSo\Imap\ImapClient->Login('john@doe....', 'john#doe', '')
#4 /usr/local/cpanel/base/3rdparty/afterlogic/modules/Mail/Managers/Main/Manager.php(2570): Aurora\Modules\Mail\Managers\Main\Manager->_getImapClient(Object(Aurora\Modules\Mail\Classes\Account), 20, 120)
#5 /usr/local/cpanel/base/3rdparty/afterlogic/modules/Mail/Module.php(1538): Aurora\Modules\Mail\Managers\Main\Manager->getMessageList(Object(Aurora\Modules\Mail\Classes\Account), 'INBOX', 0, 20, '', false, Array, '')
#6 [internal function]: Aurora\Modules\Mail\Module->GetMessages(383, 'INBOX', 0, 20, '', 'flagged', false, '')
#7 /usr/local/cpanel/base/3rdparty/afterlogic/system/Module/AbstractModule.php(876): call_user_func_array(Array, Array)
#8 /usr/local/cpanel/base/3rdparty/afterlogic/modules/Core/Module.php(536): Aurora\System\Module\AbstractModule->CallMethod('GetMessages', Array, true)
#9 [internal function]: Aurora\Modules\Core\Module->EntryApi()
#10 /usr/local/cpanel/base/3rdparty/afterlogic/system/Module/AbstractModule.php(621): call_user_func_array(Array, Array)
#11 /usr/local/cpanel/base/3rdparty/afterlogic/system/Module/Manager.php(690): Aurora\System\Module\AbstractModule->RunEntry('api')
#12 /usr/local/cpanel/base/3rdparty/afterlogic/system/Application.php(89): Aurora\System\Module\Manager->RunEntry('api')
#13 /usr/local/cpanel/base/3rdparty/afterlogic/index.php(21): Aurora\System\Application::Start()
#14 {main}

Can you guys help me with some information?
Thank you so much!

**Comment by AldoSouzaNeto** [comment]
Sorry guys! This issue is related to Webmail-Lite8. I'll move this to the right page.
